"""
Query geometry — read model file path, nodes, bars, load cases, and combinations.

Works with any open model (analysis not required).
All values are in Robot's internal SI units (N, m, Pa, rad).
"""

import pyrobotstructural

dll_path = r"C:\Program Files\Autodesk\Robot Structural Analysis Professional 2026\Exe\Interop.RobotOM.dll"

pyrobotstructural.initialize(dll_path)
app = pyrobotstructural.RobotApp()

# =============================================================================
# 1. MODEL — file path
# =============================================================================

print("=" * 60)
print("MODEL")
print("=" * 60)

model_path = app.query.model.get_model_path()
print(f"  Model directory: {model_path}")

# =============================================================================
# 2. NODES — coordinates
# =============================================================================

print()
print("=" * 60)
print("NODES")
print("=" * 60)

# All nodes as a plain list — quickest way to inspect the model
node_list = app.query.nodes.get_all_in_list()
print(f"  Total nodes: {len(node_list)}")
print("Printing first 5 nodes data:")
for nr, x, y, z in node_list[:5]:
    print(f"  {nr:>5}  {x:>10.4f}  {y:>10.4f}  {z:>10.4f}")

# Individual node access — get node 1 by index
node = app.query.nodes.get_node(1)
print(f"\n  Node 1 (by index): number={node.Number}  IsCalc={node.IsCalc}")

# Convenience wrapper for coordinates
coords = app.query.nodes.get_node_coords(node)
print(f"  Node 1 coords: X={coords[0]:.4f}  Y={coords[1]:.4f}  Z={coords[2]:.4f}")

# Exclude calculation nodes (auto-generated by FE mesh or analysis)
real_nodes = app.query.nodes.get_all(exclude_calc_nodes=True)
print(f"\n  User-defined nodes (exclude calc): {len(real_nodes)}")

# =============================================================================
# 3. BARS — topology and section properties
# =============================================================================

print()
print("=" * 60)
print("BARS")
print("=" * 60)

# Topology: bar number + start/end node numbers
bar_topo = app.query.bars.get_all_bars_node_numbers()
print(f"  Total bars: {len(bar_topo)}")
print(f"  {'Bar':>5}  {'Start node':>12}  {'End node':>10}")
for bar_nr, start, end in bar_topo:
    print(f"  {bar_nr:>5}  {start:>12}  {end:>10}")

# Individual bar — section name and material
if bar_topo:
    first_bar_nr = bar_topo[0][0]
    bar = app.query.bars.get_bar(first_bar_nr)
    if bar is not None:
        print(f"\n  Bar {first_bar_nr}:")
        print(f"    Start node : {bar.StartNode}")
        print(f"    End node   : {bar.EndNode}")
        print(f"    IsSuperBar : {bar.IsSuperBar}")
        section = app.query.bars.get_bar_section_data(bar)
        print(f"    Section    : {section.Name}")

# =============================================================================
# 4. LOAD CASES — names, numbers, natures
# =============================================================================

print()
print("=" * 60)
print("LOAD CASES")
print("=" * 60)

all_cases = app.query.loadcases.get_all_load_cases()
print(f"  Total cases (simple + combinations): {all_cases.Count}")

# Walk through and print simple load cases
print(f"\n  {'Nr':>5}  {'Name':<30}  {'Nature':>6}  {'Type':>6}")
for i in range(1, all_cases.Count + 1):
    lcase = app.query.loadcases.get_simple_loadcase(case_index=i)
    # lcase.Type: 0 = simple, 1 = combination
    if int(lcase.Type) == 0:
        print(
            f"  {lcase.Number:>5}  {lcase.Name:<30}  {int(lcase.Nature):>6}  {int(lcase.AnalizeType):>6}"
        )

# Access a specific case by its user-assigned number (e.g. case 2)
case1 = app.query.loadcases.get_simple_loadcase(number=2)
print(f"\n  Case number=2: name='{case1.Name}'")

# =============================================================================
# 5. COMBINATIONS — names, numbers, types
# =============================================================================

print()
print("=" * 60)
print("COMBINATIONS")
print("=" * 60)

# Return as plain list of [name, number, comb_type_string]
comb_list = app.query.combinations.get_all(return_objects=False)
print(f"  Total combinations: {len(comb_list)}")
if comb_list:
    print(f"  {'Nr':>5}  {'Name':<30}  {'Type':>6}")
    for name, number, comb_type in comb_list:
        print(f"  {number:>5}  {name:<30}  {comb_type:>6}")

print()
print("Geometry query complete.")
